"""empty message

Revision ID: 24ccd86197ec
Revises: None
Create Date: 2016-03-26 17:52:23.447893

"""

# revision identifiers, used by Alembic.
revision = '24ccd86197ec'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('description2', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist', 'description2')
    ### end Alembic commands ###
