"""empty message

Revision ID: a5ec10dd81e9
Revises: None
Create Date: 2016-04-02 00:19:49.641968

"""

# revision identifiers, used by Alembic.
revision = 'a5ec10dd81e9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('thumbnail', sa.String(length=500), nullable=True))
    op.add_column('wishlist', sa.Column('url', sa.String(length=500), nullable=True))
    op.drop_column('wishlist', 'imgUrl')
    op.drop_column('wishlist', 'itemUrl')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist', sa.Column('itemUrl', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('wishlist', sa.Column('imgUrl', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('wishlist', 'url')
    op.drop_column('wishlist', 'thumbnail')
    ### end Alembic commands ###
