"""empty message

Revision ID: b08d18eb0419
Revises: 344e42afcf57
Create Date: 2016-03-26 21:58:01.675860

"""

# revision identifiers, used by Alembic.
revision = 'b08d18eb0419'
down_revision = '344e42afcf57'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('firstname', sa.String(length=30), nullable=True),
    sa.Column('lastname', sa.String(length=30), nullable=True),
    sa.Column('image', sa.String(length=30), nullable=True),
    sa.Column('sex', sa.String(length=6), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('profile_added_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('username')
    )
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column(u'user', 'username')
    op.drop_column(u'user', 'lastname')
    op.drop_column(u'user', 'firstname')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column('firstname', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column(u'user', sa.Column('lastname', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column(u'user', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_table('profile')
    ### end Alembic commands ###
